apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- config-patch.yaml
images:
- name: docker.io/codeform/hello-api
  newTag: v1.3.0
namespace: abc
